# Generated by Django 5.0.4 on 2024-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
