# Generated by Django 5.0.4 on 2024-04-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
